### ISSUE TITLE
Gem does not work as per documentation in ruby 2.3.0

### ISSUE THREAD

**Issue by weshatheleopard** [djberg96/attempt#3]
```
2.3.5 :001 > gem 'attempt'
 => true
2.3.5 :002 > attempt(2, 20) { "test" }
ArgumentError: wrong number of arguments (given 2, expected 0)
        from /[censored]/.bundle/gems/ruby/2.3.0/gems/attempt-0.4.0/lib/attempt.rb:127:in `attempt'
        from (irb):2
```

I looked at the line mentioned above and I don't see any reason why it should not be working as intended... but it does not.

**Comment by djberg96** [comment]
@weshatheleopard In 0.4.0 and later I switched it to kwargs. Please try `attempt(tries: 2, interval: 20) { "test" } `

**Comment by weshatheleopard** [comment]
Can you please update your README accodingly?

**Comment by djberg96** [comment]
@weshatheleopard Certainly. I've just updated the wiki, too.

**Comment by weshatheleopard** [comment]
Also I think you need to rename your `README` to `README.rdoc` for the markup to work properly on github.

**Comment by djberg96** [comment]
Ok, I've updated the README. Thanks for letting me know.
